spring:
  application:
    name: file-storage-service

storage:
  provider: ${STORAGE_PROVIDER:minio_local}
  bucket-name: ${STORAGE_BUCKET:first}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:admin123}